# Generated by Django 3.0.4 on 2020-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Rock with Stace is among the best online storefront sellers as we offer the best affordable prices on legit commodities that meet the required customer standards.'),
            preserve_default=False,
        ),
    ]
